---
glob: "**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      Style/FrozenStringLiteralComment:
        Enabled: false
      inherit_from:
        - .rubocop.yml
